const mongoose = require("mongoose");

const clientSchema = mongoose.Schema({
    nombre: { type: String, required: false },
    apellido: { type: String, required: false },
    email: { type: String, required: false, lowercase: true },
    telefono: { type: String, required: false },
    cedula: { type: String, required: false },
    mensualidad: { type: String, required: false },
    velocidad: { type: String, required: false },
    cedulaURL: { type: String, required: false },
    firmaURL: { type: String, required: false },
    latitud: { type: String, required: false },
    longitud: { type: String, required: false },
    tipoDeVivienda: { type: String, required: false, default: 'Edificio' },
    tipoDeServicio: { type: String, required: false, default: 'Residencial' },
    nombreDeVivienda: { type: String, required: false, default: '' },
    numeroDeVivienda: { type: String, required: false, default: '' },
    montoInstalacion: { type: Number, required: false },
    serviciosContratados: [{ type: String, required: false }],
    modeloONU: { type: String, required: false },
    macONU: { type: String, required: false },
    serialONU: { type: String, required: false },
    potenciaONU: { type: Number, required: false },
    metrosDrop: { type: Number, required: false },
    metrosUTP: { type: Number, required: false },
    conectoresSC: { type: Number, required: false },
    nap: { type: String, required: false },
    puertoNap: { type: Number, required: false },
    marcaRouterCliente: { type: String, required: false },
    macRouterCliente: { type: String, required: false },
    medicionURL: { type: String, required: false },
    rutaURL: { type: String, required: false },
    posicionURL: { type: String, required: false },
    fechaDeInstalacion: { type: String, required: false },
    notas: { type: String, required: false },
    totalRecaudado: { type: Number, required: false },
    fechaDePago: { type: String, required: false },
    metodoDePago: { type: String, required: false },
    comprobanteURL: { type: String, required: false },
    numeroReferencia: { type: String, required: false },
    titularCuenta: { type: String, required: false },
    contratoURL: { type: String, required: false },
    reporteURL: { type: String, required: false },
    bienvenidaURL: { type: String, required: false },
    reciboURL: { type: String, required: false },
    idCRM: { type: Number, required: false },
    serviceIdCRM: { type: Number, required: false },
    facturaIdCRM: { type: Number, required: false },
    enviadoCorreoCliente: { type: Boolean, required: false },
    enviadoCorreoInterno: { type: Boolean, required: false },
    activoEnTV: { type: Boolean, required: false, default: false },
    activoEnCRM: { type: Boolean, required: false, default: false },
    estaActivado: { type: Boolean, required: false, default: false },
    contratoExpressPath: { type: String, required: false, default: '' },
    bienvenidaExpressPath: { type: String, required: false, default: '' },
    reporteExpressPath: { type: String, required: false, default: '' },
    reciboPagoExpressPath: { type: String, required: false, default: '' },
    vendedor: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true }
}, { timestamps: true })



const Client = mongoose.model("client", clientSchema)

module.exports = Client;